version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "rffontenelle"
    commit-message:
      prefix: "gha"
    groups:
       all-github-actions:
          patterns:
            - "*"
      
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "rffontenelle"
    commit-message:
      prefix: "pip"
    groups:
       all-pip-packages:
          patterns:
            - "*"
